server:
  port: 8082
spring:
  application:
    name: cart
  rabbitmq:
    host: 115.29.168.73
    port: 5672
    username: neuedu
    password: Goway730208
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIGSERVER
      profile: dev

